# Generated by Django 3.0.4 on 2020-04-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_location',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
